name: Upload Release Asset

on:
  push:
    tags:
    - '[0-9]+.[0-9]+.[0-9]*'

jobs:
  build:
    name: Upload Release Asset
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0 # git describeするために履歴を取得

    # get the node version from the .node-version file
    - name: Read .node-version
      run: echo "##[set-output name=NODEVERSION;]$(cat .node-version)"
      id: nodenv

    - name: Setup Node.js (.node-version)
      uses: actions/setup-node@v1
      with:
        node-version: "${{ steps.nodenv.outputs.NODEVERSION }}"

    - name: Npm install
      run: npm install

    - name: Npm build
      run: npm run build

    - name: Plugin zip
      run: npm run plugin-zip

    # チェンジログをlerna-changelogで生成する
    - name: Create Changelog
      env:
        GITHUB_AUTH: ${{ secrets.ACCESS_GITHUB_TOKEN }}
      run: |
        # Get PrevTag From git
        PREV_TAG=$(git describe –abbrev=0)
        LATEST_TAG=${{ github.event.pull_request.title }}

        npx lerna-changelog –from=$PREV_TAG > ./RELEASE_NOTE$LATEST_TAG.md
        cat ./RELEASE_NOTE$LATEST_TAG.md

    # softprops/action-gh-release@v1でリリース
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        name: Release ${{ github.event.pull_request.title }}
        tag_name: ${{ github.event.pull_request.title }}
        body_path: ./RELEASE_NOTE${{ github.event.pull_request.title }}.md
        draft: false
        prerelease: false


