name: Create Release

on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.event.pull_request.title }} #v0.1.〇〇
          release_name: ${{ github.event.pull_request.title }}
          body: ${{ github.event.pull_request.body }}
          draft: false
          prerelease: false
      - name: Checkout code
        uses: actions/checkout@v2
      - run: |
           echo "${{ github.event.pull_request.title }}" > TAG_NAME
           git tag ${{ github.event.pull_request.title }}
           git push origin ${{ github.event.pull_request.title }}
      - name: Checkout code
      - uses: actions/checkout@master
      - name: Build # Remove or modify this step as needed
      - run: |
          npm install
          npm run build
      - name: WordPress Plugin Deploy
      - uses: 10up/action-wordpress-plugin-deploy@stable
        env:
          SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
          SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
          SLUG: flip-box-block
